// Auto-generated by @staticview/cli

import type { GraphEditorTypes } from "../graph-editor.ts";

declare const GraphEditorName: GraphEditorTypes["ComponentName"];

declare global {
  interface HTMLElementTagNameMap {
    /**
     * `graph-editor` edits a cubic bezier easing curve on a zoomable panel.The curve is a path made of one `M` command and one or
     * more `C` commands, drawn inside a square viewBox of `PATH_SVG_VIEW_BOX_SIZE`. Every anchor point carries two control
     * points, and dragging either one reshapes the curve.
     *
     * ```html
     * <graph-editor></graph-editor>
     * ```
     *
     * ## Reading and writing the curve
     *
     * `points` holds the commands. Read `points.value` for the numbers and `points.valueStr` for the path string.
     *
     * ```js
     * const editor = document.querySelector("graph-editor");
     *
     * editor.setFromPathStr("M 0 1 C 0.61 0 0.88 0 1 0");
     * editor.points.events.onUpdate.add(() => console.log(editor.points.valueStr));
     * ```
     *
     * `setFromPathStr` returns `false` and logs when the string does not follow `M x y C cx1 cy1 cx2 cy2 x y`. Pass commands
     * directly with `setFromPoints` to skip the parsing.
     *
     * The `complete` event fires once an edit settles, which is the point to persist the curve. `points.events.onUpdate` fires on
     * every change instead, including while dragging.
     *
     * ## Panning and zooming
     *
     * The wheel zooms, and holding the pan key drags the panel. Both are on by default and turn off through `settings`:
     *
     * ```js
     * editor.settings.zoomEnabled = false;
     * editor.settings.panEnabled = false;
     * ```
     *
     * `zoomIn` and `zoomOut` step by `settings.zoomStep`, staying inside `settings.zoomMin` and `settings.zoomMax`. Double
     * clicking the panel re-centers it.
     *
     * ## Snapping
     *
     * Anchor points and control points snap separately, each to the grid, to other anchors, and to other control points. Every
     * combination is its own flag on `settings`, so a curve can snap to the grid while ignoring nearby points:
     *
     * ```js
     * editor.settings.anchorSnapToGrid = true;
     * editor.settings.anchorSnapToOtherAnchors = false;
     * ```
     *
     * `autoHidePoints` hides the anchor and control points until the path takes focus.
     *
     * ## History
     *
     * Point edits go through `historyManager`, which keeps up to `settings.maxHistory` steps. The undo and redo keys live in
     * `settings` as `undoKeys` and `redoKeys`.
     */
    [GraphEditorName]: GraphEditorTypes["Instance"];
  }
}

export {};
